### ISSUE TITLE
Unsubscribe from subscription to release resources

### ISSUE THREAD

**Issue by maurelio1234** [xcomponent/ReactiveXComponent.js#75]
We actually do not unsubscribe from subscriptions.

https://github.com/ReactiveX/rxjs/blob/master/doc/subscription.md

**Comment by mbarekh** [comment]
We do have a dispose method in xcWebSocketSubscriber.ts. I didin't really get the difference with the unsubscribe or cancel methods of RxJs but it works fine. We also need to call dispose on every subscriber when closing the session.

**Comment by maurelio1234** [comment]
If I'm not wrong we call dispose on the subscribers already. I'm more
worried on all subscriptions we create on the subscribers that we do not
dispose. I'd like to see more examples on how unsubscribe is supposed to be
called. In the end, I think at using rx to manage short lived subscriptions
whereas it seems to be made to manage more long lived scenarios.

**Comment by nicolaserny** [comment]
Best practice to unsubscribe Observable collections:
`https://medium.com/@benlesh/rxjs-dont-unsubscribe-6753ed4fda87`

**Comment by nicolaserny** [comment]
[](url)

**Comment by Julien-Molina** [comment]
Done during a previous refactoring in : WebSocketBridgeCommunication.ts
