### ISSUE TITLE
Fix imports of xcomponent types

### ISSUE THREAD

**Issue by nicolaserny** [xcomponent/ReactiveXComponent.js#84]
Currently many xcomponent imports are too complicated.
For instance:
import { Session } from 'reactivexcomponent.js/lib/types/communication/xcSession';

it should be:
import { Session } from 'reactivexcomponent.js';

To do that, export all types in the index file

**Comment by mbarekh** [comment]
All types are allready exported in the index file, and you can allready import using "import { Session } from 'reactivexcomponent.js'"

**Comment by nicolaserny** [comment]
@mbarekh did you try your import ? Perhaps it is fixed with the latest version. I think it was an issue with a xcomponent v4 compatible API

**Comment by mbarekh** [comment]
@nicolaserny This import is used in the spy web
https://github.com/xcomponent/SpyXComponent.js/blob/master/src/utils/sessionXCSpy.ts
