### ISSUE TITLE
Avoid importing the whole rxjs api

### ISSUE THREAD

**Issue by nicolaserny** [xcomponent/ReactiveXComponent.js#88]
Import only the operators you need.
(reduce the size of js bundles)
For example:
import 'rxjs/add/operator/map';

**Comment by mbarekh** [comment]
We have only one import "import { Observable } from "rxjs/Rx";" (Cf xcWebSocketSubscriber.ts)
I don't think that adding the suggested import will help to reduce the size of js bundles

**Comment by nicolaserny** [comment]
@mbarekh and when we use map, filter... operators ?
Check the following link
[https://gist.github.com/MichalZalecki/d78c52ec55d7ec7b53f7](https://gist.github.com/MichalZalecki/d78c52ec55d7ec7b53f7)

**Comment by mbarekh** [comment]
@nicolaserny map, filter operators are methods related to the Observable object that is allready imported. Those additional imports are useless.
